# 配置网关 Port:3000
spring:
  cloud:
    gateway:
      routes:
        # user service Port:3001
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        # static service Port:3002
        - id: static-service
          uri: lb://static-service
          predicates:
            - Path=/public/**
        # carousel service Port:3003
        - id: carousel-service
          uri: lb://carousel-service
          predicates:
            - Path=/carousel/**
        # product service Port:3004
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        # cart service Port:3009
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        # order service Port:3010
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        # challenge service:3012
        - id: challenge-service
          uri: lb://challenge-service
          predicates:
            - Path=/challenge/**
        # websocket service Port:3013
        - id: websocket-service
          uri: lb://websocket-service
          predicates:
            - Path=/notify/**
