# 配置网关
spring:
  cloud:
    gateway:
      routes:
        # user service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
        # product service
        - id: product-service # 此名称随意定义
          uri: lb://product-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/product/** # 访问product相关,转发到product服务
        # carousel service
        - id: carousel-service  # 轮播图服务
          uri: lb://carousel-service #静态资源处理以及oss上传服务!
          predicates:
            - Path=/carousel/**
        # cart service
        - id: cart-service  # 购物车服务
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        # order service
        - id: order-service  # 订单服务
          uri: lb://order-service
          predicates:
            - Path=/order/**
        # challenge service
        - id: challenge-service  # 挑战服务
          uri: lb://challenge-service
          predicates:
            - Path=/challenge/**